import "CharactherViewModel.idl";

namespace DragonsAndDungeonsCaptureAge
{
    [bindable]
    [default_interface]
    runtimeclass CharacterSelectButtonControl : Windows.UI.Xaml.Controls.UserControl, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        CharacterSelectButtonControl();
        
        CharactherViewModel CharacterEntry;

        String CharacterName;

        Windows.Foundation.Collections.IObservableVector<CharactherViewModel> CharacterEntities{ get; };
    }
}
