namespace DragonsAndDungeonsCaptureAge
{
    [default_interface]
    runtimeclass CharacterStatControl : Windows.UI.Xaml.Controls.UserControl
    {
        CharacterStatControl();

        Int16 CharacterStatValue;
    }
}
