import "CharactherViewModel.idl";

namespace DragonsAndDungeonsCaptureAge

{   
    [bindable]
    [default_interface]
    runtimeclass CharachterSelectionPanelControl : Windows.UI.Xaml.Controls.UserControl, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        CharachterSelectionPanelControl();
        
        static Windows.UI.Xaml.DependencyProperty CharacterEntitiesProperty{ get; };
        Windows.Foundation.Collections.IObservableVector<CharactherViewModel> CharacterEntities;

        UInt32 CharacterCount;
    }
}
