import "CharactherViewModel.idl";

namespace DragonsAndDungeonsCaptureAge
{
    [bindable]
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        
        Windows.Foundation.Collections.IObservableVector<CharactherViewModel> CharacterEntities{ get; };
    }
}
